name: room-booking-core-services - dev
values:
  - key: baseUrl
    value: 'https://53e2d511-c77e-464c-a0d4-9e69793dfcc1.mock.pstmn.io'
  - key: CI
    value: 'true'
  - key: RESPONSE_TIME_THRESHOLD
    value: '2000'
  - key: AWS_ACCESS_KEY_ID
    value: ''
  - key: AWS_SECRET_ACCESS_KEY
    value: ''
  - key: AWS_REGION
    value: eu-west-2
  - key: AWS_SECRET_NAME
    value: api-credentials-dev
